var hierarchy =
[
    [ "xml_parser::Author", "structxml__parser_1_1_author.html", null ],
    [ "auto_deleter< T >", "structauto__deleter.html", null ],
    [ "axis_to_type< N >", "structaxis__to__type.html", null ],
    [ "xpath_parser::binary_op_t", "structxpath__parser_1_1binary__op__t.html", null ],
    [ "xml_parser::Block", "structxml__parser_1_1_block.html", null ],
    [ "check", "classcheck.html", null ],
    [ "xml_parser::ClassName", "structxml__parser_1_1_class_name.html", null ],
    [ "CMakeGen", "class_c_make_gen.html", null ],
    [ "Code", "class_code.html", null ],
    [ "document_order_comparator", "structdocument__order__comparator.html", null ],
    [ "equal_to", "structequal__to.html", null ],
    [ "std::exception", null, [
      [ "pugi::xpath_exception", "classpugi_1_1xpath__exception.html", null ]
    ] ],
    [ "gap", "structgap.html", null ],
    [ "xml_parser::GetOptSetup", "structxml__parser_1_1_get_opt_setup.html", null ],
    [ "parse::getOptsParse", "classparse_1_1get_opts_parse.html", null ],
    [ "xml_parser::HeaderFileName", "structxml__parser_1_1_header_file_name.html", null ],
    [ "Help", "class_help.html", null ],
    [ "latin1_decoder", "structlatin1__decoder.html", null ],
    [ "latin1_writer", "structlatin1__writer.html", null ],
    [ "less", "structless.html", null ],
    [ "less_equal", "structless__equal.html", null ],
    [ "mainGenerator", "classmain_generator.html", null ],
    [ "name_null_sentry", "structname__null__sentry.html", null ],
    [ "xml_parser::NameSpace", "structxml__parser_1_1_name_space.html", null ],
    [ "namespace_uri_predicate", "structnamespace__uri__predicate.html", null ],
    [ "not_equal_to", "structnot__equal__to.html", null ],
    [ "opt_false", "structopt__false.html", null ],
    [ "opt_true", "structopt__true.html", null ],
    [ "xml_parser::Option", "structxml__parser_1_1_option.html", null ],
    [ "xml_parser::Options", "structxml__parser_1_1_options.html", null ],
    [ "xml_parser::OverAllDescription", "structxml__parser_1_1_over_all_description.html", null ],
    [ "xml_parser::Sample", "structxml__parser_1_1_sample.html", null ],
    [ "xml_parser::SampleUsage", "structxml__parser_1_1_sample_usage.html", null ],
    [ "Sort", "class_sort.html", null ],
    [ "xml_parser::SourceFileName", "structxml__parser_1_1_source_file_name.html", null ],
    [ "strconv_attribute_impl< opt_escape >", "structstrconv__attribute__impl.html", null ],
    [ "strconv_pcdata_impl< opt_trim, opt_eol, opt_escape >", "structstrconv__pcdata__impl.html", null ],
    [ "utf16_counter", "structutf16__counter.html", null ],
    [ "utf16_decoder< opt_swap >", "structutf16__decoder.html", null ],
    [ "utf16_writer", "structutf16__writer.html", null ],
    [ "utf32_counter", "structutf32__counter.html", null ],
    [ "utf32_decoder< opt_swap >", "structutf32__decoder.html", null ],
    [ "utf32_writer", "structutf32__writer.html", null ],
    [ "utf8_counter", "structutf8__counter.html", null ],
    [ "utf8_decoder", "structutf8__decoder.html", null ],
    [ "utf8_writer", "structutf8__writer.html", null ],
    [ "wchar_decoder", "structwchar__decoder.html", null ],
    [ "wchar_selector< size >", "structwchar__selector.html", null ],
    [ "wchar_selector< 2 >", "structwchar__selector_3_012_01_4.html", null ],
    [ "wchar_selector< 4 >", "structwchar__selector_3_014_01_4.html", null ],
    [ "xml_allocator", "structxml__allocator.html", [
      [ "xml_document_struct", "structxml__document__struct.html", null ]
    ] ],
    [ "pugi::xml_attribute", "classpugi_1_1xml__attribute.html", null ],
    [ "pugi::xml_attribute_iterator", "classpugi_1_1xml__attribute__iterator.html", null ],
    [ "pugi::xml_attribute_struct", "structpugi_1_1xml__attribute__struct.html", null ],
    [ "xml_buffered_writer", "classxml__buffered__writer.html", null ],
    [ "xml_extra_buffer", "structxml__extra__buffer.html", null ],
    [ "xml_memory_management_function_storage< T >", "structxml__memory__management__function__storage.html", null ],
    [ "xml_memory_page", "structxml__memory__page.html", null ],
    [ "xml_memory_string_header", "structxml__memory__string__header.html", null ],
    [ "pugi::xml_named_node_iterator", "classpugi_1_1xml__named__node__iterator.html", null ],
    [ "pugi::xml_node", "classpugi_1_1xml__node.html", [
      [ "pugi::xml_document", "classpugi_1_1xml__document.html", null ]
    ] ],
    [ "pugi::xml_node_iterator", "classpugi_1_1xml__node__iterator.html", null ],
    [ "pugi::xml_node_struct", "structpugi_1_1xml__node__struct.html", null ],
    [ "xml_node_struct", null, [
      [ "xml_document_struct", "structxml__document__struct.html", null ]
    ] ],
    [ "pugi::xml_object_range< It >", "classpugi_1_1xml__object__range.html", null ],
    [ "pugi::xml_parse_result", "structpugi_1_1xml__parse__result.html", null ],
    [ "xml_parser", "structxml__parser.html", null ],
    [ "xml_stream_chunk< T >", "structxml__stream__chunk.html", null ],
    [ "pugi::xml_text", "classpugi_1_1xml__text.html", null ],
    [ "pugi::xml_tree_walker", "classpugi_1_1xml__tree__walker.html", null ],
    [ "pugi::xml_writer", "classpugi_1_1xml__writer.html", [
      [ "pugi::xml_writer_file", "classpugi_1_1xml__writer__file.html", null ],
      [ "pugi::xml_writer_stream", "classpugi_1_1xml__writer__stream.html", null ]
    ] ],
    [ "xpath_allocator", "structxpath__allocator.html", null ],
    [ "xpath_allocator_capture", "structxpath__allocator__capture.html", null ],
    [ "xpath_ast_node", "classxpath__ast__node.html", null ],
    [ "xpath_context", "structxpath__context.html", null ],
    [ "xpath_lexer", "classxpath__lexer.html", null ],
    [ "xpath_lexer_string", "structxpath__lexer__string.html", null ],
    [ "xpath_memory_block", "structxpath__memory__block.html", null ],
    [ "pugi::xpath_node", "classpugi_1_1xpath__node.html", null ],
    [ "pugi::xpath_node_set", "classpugi_1_1xpath__node__set.html", null ],
    [ "xpath_node_set_raw", "classxpath__node__set__raw.html", null ],
    [ "pugi::xpath_parse_result", "structpugi_1_1xpath__parse__result.html", null ],
    [ "xpath_parser", "structxpath__parser.html", null ],
    [ "pugi::xpath_query", "classpugi_1_1xpath__query.html", null ],
    [ "xpath_query_impl", "structxpath__query__impl.html", null ],
    [ "xpath_stack", "structxpath__stack.html", null ],
    [ "xpath_stack_data", "structxpath__stack__data.html", null ],
    [ "xpath_string", "classxpath__string.html", null ],
    [ "pugi::xpath_variable", "classpugi_1_1xpath__variable.html", null ],
    [ "xpath_variable", null, [
      [ "xpath_variable_boolean", "structxpath__variable__boolean.html", null ],
      [ "xpath_variable_node_set", "structxpath__variable__node__set.html", null ],
      [ "xpath_variable_number", "structxpath__variable__number.html", null ],
      [ "xpath_variable_string", "structxpath__variable__string.html", null ]
    ] ],
    [ "pugi::xpath_variable_set", "classpugi_1_1xpath__variable__set.html", null ]
];